from django.conf.urls import url
from . import views

app_name = 'drodos'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.loginp, name='loginp'),
    url(r'^logout/$', views.logoutp, name='logoutp'),
    url(r'^checklogin/$', views.checklogin, name='checklogin'),
    url(r'^register/$', views.register, name='register'),
    url(r'^checkregister/$', views.checkregister, name='checkregister'),
    url(r'^registerfail/$', views.registerfail, name='registerfail',),
    url(r'^registered/$', views.registered, name='registered'),
    url(r'^user/(?P<username>.+)$', views.user, name='user'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^upload2/$', views.upload2, name='upload2'),
    url(r'^uploaded/(?P<filename>.+)$', views.uploaded, name='uploaded'),
    url(r'^files/$', views.files, name='files'),
    url(r'^file/(?P<filename>.+)$', views.file, name='file'),
    url(r'^changesettings/(?P<filename>.+)$', views.changesettings, name='changesettings'),
    url(r'^deletefile/(?P<filename>.+)$', views.deletefile, name='deletefile'),
    url(r'^download/(?P<filename>.+)$', views.download, name='download'),
    url(r'^groups/$', views.groups, name='groups'),
    url(r'^group/(?P<groupname>.+)/$', views.group, name='group'),
    url(r'^group/(?P<groupname>.+)/viewgroup$', views.viewgroup, name='viewgroup'),
    url(r'^group/(?P<groupname>.+)/invitemember$', views.invitemember, name='invitemember'),
    url(r'^group/(?P<groupname>.+)/removemember$', views.removemember, name='removemember'),
    url(r'^group/(?P<groupname>.+)/removedmember$', views.removedmember, name='removedmember'),
    url(r'^group/(?P<groupname>.+)/addfile$', views.addfile, name='addfile'),
    url(r'^group/(?P<groupname>.+)/removefile$', views.removefile, name='removefile'),
    url(r'^group/(?P<groupname>.+)/addedfile$', views.addedfile, name='addedfile'),
    url(r'^group/(?P<groupname>.+)/removedfile$', views.removedfile, name='removedfile'),
    url(r'^group/(?P<groupname>.+)/sendgroupinvite$', views.sendgroupinvite, name='sendgroupinvite'),
    url(r'^group/(?P<groupname>.+)/leavegroup$', views.leavegroup, name='leavegroup'),
    url(r'^group/(?P<groupname>.+)/deletegroup$', views.deletegroup, name='deletegroup'),
    url(r'^myprofile/$', views.myprofile, name='myprofile'),
    url(r'^managegroups/creategroup/$', views.creategroup, name='creategroup'),
    url(r'^managegroups/invites/$', views.invites, name='invites'),
    url(r'^answerinvite/(?P<groupid>[0-9]+)/$', views.answerinvite, name='answerinvite'),
    url(r'^managegroups/$', views.managegroups, name='managegroups'),
    url(r'^savegroup/$', views.savegroup, name='savegroup'),
    url(r'^premium/$', views.premium, name='premium'),
    url(r'^gopremium/$', views.gopremium, name='gopremium'),
    url(r'^gonormal/$', views.gonormal, name='gonormal'),
    url(r'^testing/$', views.testing, name='testing'),
]
