# Generated by Django 2.0.4 on 2018-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0004_auto_20180502_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='maxStorage',
            field=models.IntegerField(default=100),
        ),
    ]
