# Generated by Django 2.0.4 on 2018-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0006_storeditem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeditem',
            name='item',
        ),
        migrations.AddField(
            model_name='storeditem',
            name='fileUrl',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
