# Generated by Django 2.0.4 on 2018-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0008_auto_20180504_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeditem',
            name='fileUrl',
            field=models.CharField(default='nourl', max_length=100),
        ),
    ]
