# Generated by Django 2.0.4 on 2018-05-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0011_auto_20180506_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fileUrl', models.CharField(default='nourl', max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
