# Generated by Django 2.0.4 on 2018-05-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0014_auto_20180506_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempItem',
        ),
    ]
