# Generated by Django 2.0.4 on 2018-05-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0015_delete_tempitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
