# Generated by Django 2.0.4 on 2018-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0018_auto_20180507_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
