# Generated by Django 2.0.4 on 2018-05-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0019_auto_20180507_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
