# Generated by Django 2.0.4 on 2018-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0021_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='item',
            field=models.ManyToManyField(related_name='item', to='sitepr.StoredItem'),
        ),
    ]
