# Generated by Django 2.0.4 on 2018-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0022_group_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeditem',
            name='groupOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeditem',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeditem',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
