# Generated by Django 2.0.4 on 2018-05-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0023_auto_20180508_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeditem',
            old_name='public',
            new_name='private',
        ),
        migrations.RemoveField(
            model_name='storeditem',
            name='password',
        ),
    ]
