# Generated by Django 2.0.4 on 2018-05-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0025_auto_20180508_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeditem',
            name='groupShared',
        ),
    ]
