# Generated by Django 2.0.4 on 2018-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0026_remove_storeditem_groupshared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeditem',
            name='fileUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
