# Generated by Django 2.0.4 on 2018-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0027_auto_20180508_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentStorage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='free',
            field=models.CharField(default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maxStorage',
            field=models.IntegerField(default=100000),
        ),
    ]
