# Generated by Django 2.0.4 on 2018-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0028_auto_20180508_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='maxStorage',
            field=models.IntegerField(default=10000),
        ),
    ]
