# Generated by Django 2.0.4 on 2018-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0030_profile_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeditem',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
