# Generated by Django 2.0.4 on 2018-05-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0031_storeditem_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
