# Generated by Django 2.0.4 on 2018-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0032_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='free',
        ),
        migrations.AlterField(
            model_name='profile',
            name='maxStorage',
            field=models.IntegerField(default=1000),
        ),
    ]
