# Generated by Django 2.0.4 on 2018-05-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0034_remove_storeditem_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='maxStorage',
            field=models.IntegerField(default=10000),
        ),
    ]
