# Generated by Django 2.0.5 on 2018-05-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepr', '0035_auto_20180509_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='questao',
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
